name: Automatic Dev Release

on:
  push:
    branches: [main]

jobs:
  create_release:
    name: Release
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org
          cache: 'yarn'

      - name: Install Surge
        run: npm install -g surge

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Dev deploy
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: yarn dev:deploy
